spring:
    application:
        name: backend
    datasource:
        url: jdbc:postgresql://localhost:54321/lumber-db
        username: user
        password: user
    jpa:
        show-sql: true
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: none
    liquibase:
        enabled: true
        change-log: classpath:/db/changelog/db.changelog-master.xml

server:
    port: 8091

